### ISSUE TITLE
Foodtango Image is no longer available.

### ISSUE THREAD

**Issue by ShiNoSenshi** [scroach/rezeptdb#7]
in recipe.card.html.twig the https://foodtango.com.au/img/ui/noimage.png image was used, when no image for recipe was existing.
Sadly the https://foodtango.com.au/img/ui/noimage.png is no longer available.
Needs to be replaced!

**Comment by scroach** [comment]
Added a custom quickfix placeholder, but I'm open for suggestions 😸
